import { SiteHeader } from "@/components/layout/SiteHeader"
import { SiteFooter } from "@/components/layout/SiteFooter"

export const metadata = {
  title: "Terms of Service — TROLLMAX",
}

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />
      <main className="mx-auto max-w-2xl flex-1 px-4 py-16">
        <h1 className="mb-2 text-3xl font-bold tracking-tight">Terms of Service</h1>
        <p className="mb-8 text-sm text-muted-foreground">Last updated: March 2026</p>

        <div className="prose prose-sm prose-invert max-w-none space-y-6 text-muted-foreground">
          <section>
            <h2 className="text-lg font-semibold text-foreground">1. Acceptance</h2>
            <p>
              By using TROLLMAX you agree to these terms. If you don&apos;t agree, don&apos;t use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">2. Consent requirement</h2>
            <p>
              You may only clone voices for which you have explicit, informed consent from the voice owner.
              You may not use TROLLMAX to impersonate real individuals, create deceptive content, or
              produce material that could cause harm. Any content that violates this rule is subject to
              immediate removal.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">3. Prohibited uses</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Cloning voices without consent</li>
              <li>Impersonating public figures for fraud or deception</li>
              <li>Creating non-consensual intimate audio or video content</li>
              <li>Violating any applicable law or third-party rights</li>
              <li>Circumventing platform safety mechanisms</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">4. Intellectual property</h2>
            <p>
              You retain ownership of content you create. By sharing content publicly, you grant
              TROLLMAX a non-exclusive license to display it on share pages.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">5. Termination</h2>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms,
              at our sole discretion, with or without notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">6. Disclaimer</h2>
            <p>
              TROLLMAX is provided &quot;as is&quot; without warranties of any kind. We are not liable for
              content generated by users or for any damages arising from use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">7. Changes</h2>
            <p>
              We may update these terms at any time. Continued use after changes constitutes acceptance.
            </p>
          </section>
        </div>
      </main>
      <SiteFooter />
    </div>
  )
}
